/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.proyecto_p1_rest;


import entities.*;
import java.awt.Dimension;
import java.awt.Image;
import main.Connection;
import responses.*;

import java.util.ArrayList;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLayeredPane;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author jose
 */
public class Principal extends javax.swing.JFrame {
    
    ImageIcon logo = new ImageIcon("imgs/logo.jpg");
    ImageIcon avatar = new ImageIcon("imgs/avatar.png");
    private String user = "pruebas2", pass ="12345678b";
    private enum StateForm { UPDATE_FORM, CREATE_FORM };
    private enum Categoria { CMS, MGS, LBS };
    private StateForm stateForm;
    private Connection conection;
    ResponseGetDetails resProdDetails;
    Detail proDetails;
    String rol;

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        conection = new Connection();
        
        categoFormComBox.removeAllItems();
        categoFormComBox.addItem("CMS");
        categoFormComBox.addItem("MGS");
        categoFormComBox.addItem("LBS");
        
        rolesComboBox.removeAllItems();
        rolesComboBox.addItem("Almacen");
        rolesComboBox.addItem("Ventas");
        
        Image logoScaled = logo.getImage().getScaledInstance(100, 100, Image.SCALE_SMOOTH);
        Icon logoIcon = new ImageIcon(logoScaled);
        logoLabel.setIcon(logoIcon);
        
        Image imgAvatar = avatar.getImage().getScaledInstance(40, 40, Image.SCALE_SMOOTH);
        Icon iconAvatar = new ImageIcon(imgAvatar);
        logoUserLabel.setIcon(iconAvatar);
        
    }
    
    private void changeCard(JLayeredPane layedPanel, JPanel panel) {
        layedPanel.removeAll();
        layedPanel.add(panel);
        layedPanel.repaint();
        layedPanel.revalidate();
    }
    
    private void changeState(String code, String message )
    {
        stateLabel.setText(code+" "+message);
    }
    
    private void showMessage(String code, String mesage, int opcion){
        changeState(code, mesage);
        
        String auxMessage = (code == "-1") ? "" : "Code: "+code+"\n"+"Message: ";
        JOptionPane.showMessageDialog(
                this, 
                auxMessage+mesage, 
                (code == "-1")?"":code, 
                opcion);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        userIconLabel = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLayeredPane2 = new javax.swing.JLayeredPane();
        login = new javax.swing.JPanel();
        btnIniciarSesion = new javax.swing.JButton();
        userTextField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        logoLabel = new javax.swing.JLabel();
        rolesComboBox = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        passTextField = new javax.swing.JPasswordField();
        operations = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        isbnTextField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        searchIsbnBtn = new javax.swing.JButton();
        searchCategoryBtn = new javax.swing.JButton();
        operationsLayeredPane = new javax.swing.JLayeredPane();
        detailProdJPanel = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        detailTextArea = new javax.swing.JTextArea();
        updateButton = new javax.swing.JButton();
        deleteButton = new javax.swing.JButton();
        createButton = new javax.swing.JButton();
        prodsCateJPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        prodsCateTextArea = new javax.swing.JTextArea();
        jSeparator2 = new javax.swing.JSeparator();
        categoryTextField = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        FormProduct = new javax.swing.JPanel();
        titleFormLabel = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        isbnFormTextField = new javax.swing.JTextField();
        nameFormTextField = new javax.swing.JTextField();
        authorFormTextField = new javax.swing.JTextField();
        editorialFormTextField = new javax.swing.JTextField();
        yearFormTextField = new javax.swing.JTextField();
        priceFormTextField = new javax.swing.JTextField();
        cancelButton = new javax.swing.JButton();
        aceptButton = new javax.swing.JButton();
        categoFormComBox = new javax.swing.JComboBox<>();
        updatePassPanel = new javax.swing.JPanel();
        updatePassBtn = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        cancelUpdatePassBtn = new javax.swing.JButton();
        currentPassTextField = new javax.swing.JPasswordField();
        confiPassTextField = new javax.swing.JPasswordField();
        newPassTextField = new javax.swing.JPasswordField();
        userLabel = new javax.swing.JLabel();
        logoUserLabel = new javax.swing.JLabel();
        stateLabel = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        menu = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        updatePassMenuItem = new javax.swing.JMenuItem();

        userIconLabel.setText("gsdfgsdfgsdf");
        userIconLabel.setPreferredSize(new java.awt.Dimension(40, 40));

        setTitle("David & Joshep SA de CV");
        setBackground(new java.awt.Color(255, 51, 51));
        setPreferredSize(new java.awt.Dimension(600, 510));

        jPanel1.setBackground(new java.awt.Color(242, 255, 248));
        jPanel1.setPreferredSize(new java.awt.Dimension(600, 450));

        jLayeredPane2.setLayout(new java.awt.CardLayout());

        login.setBackground(new java.awt.Color(242, 255, 248));
        login.setPreferredSize(new java.awt.Dimension(600, 450));
        login.setLayout(new java.awt.GridBagLayout());

        btnIniciarSesion.setText("Inisiar Sesion");
        btnIniciarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIniciarSesionActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        login.add(btnIniciarSesion, gridBagConstraints);

        userTextField.setPreferredSize(new java.awt.Dimension(100, 24));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 139;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        login.add(userTextField, gridBagConstraints);

        jLabel1.setText("Usuario");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        login.add(jLabel1, gridBagConstraints);

        jLabel2.setText("Contraseña");
        jLabel2.setToolTipText("");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        login.add(jLabel2, gridBagConstraints);

        logoLabel.setAlignmentY(0.0F);
        logoLabel.setMaximumSize(new java.awt.Dimension(100, 100));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        login.add(logoLabel, gridBagConstraints);

        rolesComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        login.add(rolesComboBox, gridBagConstraints);

        jLabel5.setText("Rol");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        login.add(jLabel5, gridBagConstraints);

        passTextField.setPreferredSize(new java.awt.Dimension(240, 24));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        login.add(passTextField, gridBagConstraints);

        jLayeredPane2.add(login, "card3");

        operations.setBackground(new java.awt.Color(242, 255, 248));

        jLabel3.setText("ISBN");

        isbnTextField.setPreferredSize(new java.awt.Dimension(100, 24));

        jLabel4.setText("Categorias");

        searchIsbnBtn.setText("Buscar");
        searchIsbnBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchIsbnBtnActionPerformed(evt);
            }
        });

        searchCategoryBtn.setText("Buscar");
        searchCategoryBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchCategoryBtnActionPerformed(evt);
            }
        });

        operationsLayeredPane.setLayout(new java.awt.CardLayout());

        detailProdJPanel.setBackground(new java.awt.Color(242, 255, 248));

        detailTextArea.setColumns(20);
        detailTextArea.setRows(5);
        detailTextArea.setPreferredSize(new java.awt.Dimension(10, 10));
        jScrollPane2.setViewportView(detailTextArea);

        updateButton.setIcon(new javax.swing.ImageIcon("/home/jose/Documentos/octavo_semestre/servicios_web/proyecto/proyecto_p1_rest/imgs/lapiz.png")); // NOI18N
        updateButton.setText("Actualizar");
        updateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateButtonActionPerformed(evt);
            }
        });

        deleteButton.setIcon(new javax.swing.ImageIcon("/home/jose/Documentos/octavo_semestre/servicios_web/proyecto/proyecto_p1_rest/imgs/trash.png")); // NOI18N
        deleteButton.setText("Eliminar");
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });

        createButton.setIcon(new javax.swing.ImageIcon("/home/jose/Documentos/octavo_semestre/servicios_web/proyecto/proyecto_p1_rest/imgs/add.png")); // NOI18N
        createButton.setText("Crear Producto");
        createButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout detailProdJPanelLayout = new javax.swing.GroupLayout(detailProdJPanel);
        detailProdJPanel.setLayout(detailProdJPanelLayout);
        detailProdJPanelLayout.setHorizontalGroup(
            detailProdJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(detailProdJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addGroup(detailProdJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(createButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(deleteButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(updateButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 23, Short.MAX_VALUE))
        );
        detailProdJPanelLayout.setVerticalGroup(
            detailProdJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, detailProdJPanelLayout.createSequentialGroup()
                .addGroup(detailProdJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(detailProdJPanelLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(updateButton)
                        .addGap(6, 6, 6)
                        .addComponent(deleteButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 106, Short.MAX_VALUE)
                        .addComponent(createButton))
                    .addComponent(jScrollPane2))
                .addContainerGap())
        );

        operationsLayeredPane.add(detailProdJPanel, "card2");

        prodsCateJPanel.setBackground(new java.awt.Color(242, 255, 248));

        prodsCateTextArea.setColumns(20);
        prodsCateTextArea.setRows(5);
        jScrollPane1.setViewportView(prodsCateTextArea);

        javax.swing.GroupLayout prodsCateJPanelLayout = new javax.swing.GroupLayout(prodsCateJPanel);
        prodsCateJPanel.setLayout(prodsCateJPanelLayout);
        prodsCateJPanelLayout.setHorizontalGroup(
            prodsCateJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(prodsCateJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 569, Short.MAX_VALUE)
                .addContainerGap())
        );
        prodsCateJPanelLayout.setVerticalGroup(
            prodsCateJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(prodsCateJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        operationsLayeredPane.add(prodsCateJPanel, "card3");

        categoryTextField.setPreferredSize(new java.awt.Dimension(100, 24));
        categoryTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                categoryTextFieldActionPerformed(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        jLabel17.setIcon(new javax.swing.ImageIcon("/home/jose/Documentos/octavo_semestre/servicios_web/proyecto/proyecto_p1_rest/imgs/Book.png")); // NOI18N
        jLabel17.setText("Productos");
        jLabel17.setToolTipText("");

        javax.swing.GroupLayout operationsLayout = new javax.swing.GroupLayout(operations);
        operations.setLayout(operationsLayout);
        operationsLayout.setHorizontalGroup(
            operationsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(operationsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(operationsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator2)
                    .addComponent(operationsLayeredPane, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(operationsLayout.createSequentialGroup()
                        .addGroup(operationsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel17)
                            .addGroup(operationsLayout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(isbnTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(searchIsbnBtn)
                                .addGap(93, 93, 93)
                                .addComponent(jLabel4)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(categoryTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(searchCategoryBtn)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        operationsLayout.setVerticalGroup(
            operationsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(operationsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(operationsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(isbnTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchIsbnBtn)
                    .addComponent(jLabel4)
                    .addComponent(categoryTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchCategoryBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(operationsLayeredPane)
                .addContainerGap())
        );

        jLayeredPane2.add(operations, "card2");

        FormProduct.setBackground(new java.awt.Color(242, 255, 248));

        titleFormLabel.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        titleFormLabel.setText("TITLE-FORM");

        jLabel6.setText("Nombre");

        jLabel7.setText("Autor");

        jLabel8.setText("Editorial");

        jLabel9.setText("Año");

        jLabel10.setText("Precio");

        jLabel11.setText("ISBN");

        cancelButton.setText("Cancelar");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        aceptButton.setText("Aceptar");
        aceptButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aceptButtonActionPerformed(evt);
            }
        });

        categoFormComBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout FormProductLayout = new javax.swing.GroupLayout(FormProduct);
        FormProduct.setLayout(FormProductLayout);
        FormProductLayout.setHorizontalGroup(
            FormProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FormProductLayout.createSequentialGroup()
                .addGap(118, 118, 118)
                .addComponent(titleFormLabel))
            .addGroup(FormProductLayout.createSequentialGroup()
                .addGap(132, 132, 132)
                .addComponent(jLabel11)
                .addGap(10, 10, 10)
                .addComponent(categoFormComBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addComponent(isbnFormTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(FormProductLayout.createSequentialGroup()
                .addGap(113, 113, 113)
                .addComponent(jLabel6)
                .addGap(10, 10, 10)
                .addComponent(nameFormTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(FormProductLayout.createSequentialGroup()
                .addGap(131, 131, 131)
                .addComponent(jLabel7)
                .addGap(10, 10, 10)
                .addComponent(authorFormTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(FormProductLayout.createSequentialGroup()
                .addGap(113, 113, 113)
                .addComponent(jLabel8)
                .addGap(10, 10, 10)
                .addComponent(editorialFormTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(FormProductLayout.createSequentialGroup()
                .addGap(140, 140, 140)
                .addComponent(jLabel9)
                .addGap(10, 10, 10)
                .addComponent(yearFormTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(jLabel10)
                .addGap(34, 34, 34)
                .addComponent(priceFormTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(FormProductLayout.createSequentialGroup()
                .addGap(283, 283, 283)
                .addComponent(aceptButton)
                .addGap(20, 20, 20)
                .addComponent(cancelButton))
        );
        FormProductLayout.setVerticalGroup(
            FormProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FormProductLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(titleFormLabel)
                .addGap(15, 15, 15)
                .addGroup(FormProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(FormProductLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel11))
                    .addComponent(categoFormComBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(isbnFormTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(FormProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(FormProductLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel6))
                    .addComponent(nameFormTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(FormProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(FormProductLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel7))
                    .addComponent(authorFormTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(FormProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(FormProductLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel8))
                    .addComponent(editorialFormTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(FormProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(yearFormTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(priceFormTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(FormProductLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(FormProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10))))
                .addGap(35, 35, 35)
                .addGroup(FormProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(aceptButton)
                    .addComponent(cancelButton)))
        );

        jLayeredPane2.add(FormProduct, "card4");

        updatePassPanel.setBackground(new java.awt.Color(242, 255, 248));

        updatePassBtn.setText("Cambiar contraseña");
        updatePassBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatePassBtnActionPerformed(evt);
            }
        });

        jLabel12.setText("Actual contrseña");

        jLabel13.setText("Confirmar contrseña");

        jLabel14.setText("Nueva contrseña");

        jLabel15.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        jLabel15.setText("Cambiar contraseña");

        cancelUpdatePassBtn.setText("Cancelar");
        cancelUpdatePassBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelUpdatePassBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout updatePassPanelLayout = new javax.swing.GroupLayout(updatePassPanel);
        updatePassPanel.setLayout(updatePassPanelLayout);
        updatePassPanelLayout.setHorizontalGroup(
            updatePassPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(updatePassPanelLayout.createSequentialGroup()
                .addGap(122, 122, 122)
                .addGroup(updatePassPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(updatePassPanelLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(updatePassPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(updatePassPanelLayout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(updatePassPanelLayout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(updatePassPanelLayout.createSequentialGroup()
                        .addGroup(updatePassPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(updatePassPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(updatePassPanelLayout.createSequentialGroup()
                                    .addComponent(updatePassBtn)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(cancelUpdatePassBtn))
                                .addGroup(updatePassPanelLayout.createSequentialGroup()
                                    .addComponent(jLabel13)
                                    .addGap(20, 20, 20)
                                    .addGroup(updatePassPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(newPassTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                                        .addComponent(currentPassTextField)
                                        .addComponent(confiPassTextField))))
                            .addComponent(jLabel15))
                        .addContainerGap(115, Short.MAX_VALUE))))
        );
        updatePassPanelLayout.setVerticalGroup(
            updatePassPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(updatePassPanelLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel15)
                .addGap(20, 20, 20)
                .addGroup(updatePassPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(currentPassTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(updatePassPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(newPassTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(updatePassPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(confiPassTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                .addGroup(updatePassPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(updatePassBtn)
                    .addComponent(cancelUpdatePassBtn))
                .addGap(51, 51, 51))
        );

        jLayeredPane2.add(updatePassPanel, "card5");

        stateLabel.setText("state");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(logoUserLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(userLabel)
                .addGap(87, 87, 87))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLayeredPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 591, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(stateLabel)))
                .addContainerGap(23, Short.MAX_VALUE))
            .addComponent(jSeparator1)
            .addComponent(jSeparator3)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(userLabel)
                    .addComponent(logoUserLabel))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLayeredPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addComponent(stateLabel)
                .addContainerGap())
        );

        menu.setBackground(new java.awt.Color(113, 179, 142));

        jMenu2.setText("Sesion");

        jMenuItem1.setText("Cerrar sesion");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem1);

        updatePassMenuItem.setText("Actualizar Contraseña");
        updatePassMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatePassMenuItemActionPerformed(evt);
            }
        });
        jMenu2.add(updatePassMenuItem);

        menu.add(jMenu2);

        setJMenuBar(menu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 634, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 424, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void searchIsbnBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchIsbnBtnActionPerformed

        if(isbnTextField.getText().length() > 0)
        {
            resProdDetails = conection.getDetails(user, pass, isbnTextField.getText());
                    
            if (resProdDetails.isComplete()) 
            {
                proDetails = resProdDetails.getDetail();
                String info = "";
                info += "IBNS           " + proDetails.getIsbn() + "\n";
                info += "Nombre         " + proDetails.getName() + "\n";
                info += "Author         " + proDetails.getAuthor() + "\n";
                info += "Editorial      " + proDetails.getEditorial() + "\n";
                info += "Precio         " + proDetails.getPrice() + "\n";
                info += "Año            " + proDetails.getYear() + "\n";
                info += "Oferta         " + String.valueOf(resProdDetails.getOffer());
                detailTextArea.setText(info);
                changeCard(operationsLayeredPane, detailProdJPanel);
                changeState(
                        String.valueOf(resProdDetails.getCode()), 
                        resProdDetails.getMessage());
            }
            else
            {
                isbnTextField.setText("");
                showMessage(
                        String.valueOf(resProdDetails.getCode()), 
                        resProdDetails.getMessage(),
                        JOptionPane.ERROR_MESSAGE);
            }
        }
        else
        {
            showMessage("-1", 
                    "El cuadrode texto ISBN esta vacio", 
                    JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_searchIsbnBtnActionPerformed

    private void searchCategoryBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchCategoryBtnActionPerformed
        if( categoryTextField.getText().length() > 0)
        {
            ResponseGetProd res = conection.getProd(user, pass, categoryTextField.getText());
        
            if (res.isComplete()) {
                ArrayList<Product> products = res.getProducts();
                String data = "";
            
                for (Product product : products) 
                    data += product.getIsbn() + "\t" + product.getName() + "\n";
            
                prodsCateTextArea.setText(data);
                System.out.println(data);
                changeCard(operationsLayeredPane, prodsCateJPanel);
            }
            else
            {
                categoryTextField.setText("");
                JOptionPane.showMessageDialog(
                    this, String.valueOf(res.getCode())+" "+res.getMessage(), 
                    res.getStatus(), JOptionPane.ERROR_MESSAGE);
            }
            changeState(String.valueOf(res.getCode()), res.getMessage());
        }
        else
        {
            changeState("1", "Cuadro de texto CATEGORIA vacio");
            JOptionPane.showMessageDialog(
                    this, "Cuadro de texto CATEGORIA vacio", 
                    "", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_searchCategoryBtnActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        user = "";
        pass = "";
        userLabel.setText("");
        changeState(String.valueOf(1), "Sesión finalizada");
        changeCard(jLayeredPane2, login);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void updateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateButtonActionPerformed
      
        stateForm = StateForm.UPDATE_FORM;
        if( proDetails != null)
        {
            titleFormLabel.setText("Actualizar producto");
            
            switch(proDetails.getIsbn().substring(0, 3))
            {
                case "CMS" : categoFormComBox.setSelectedIndex(0); break;
                case "MGS" : categoFormComBox.setSelectedIndex(1); break;
                case "LBS" : categoFormComBox.setSelectedIndex(2); break;
            }
            isbnFormTextField.setText(proDetails.getIsbn().substring(3));
            nameFormTextField.setText(proDetails.getName());
            authorFormTextField.setText(proDetails.getAuthor());
            editorialFormTextField.setText(proDetails.getEditorial());
            yearFormTextField.setText(String.valueOf(proDetails.getYear()));
            priceFormTextField.setText(proDetails.getPrice());

            changeCard(jLayeredPane2, FormProduct);
        }
        else
        {
            JOptionPane.showMessageDialog(
                this, "Ningún producto seleccionado",
                "", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_updateButtonActionPerformed

    private void clearForm(){
        yearFormTextField.setText("");
        authorFormTextField.setText("");
        editorialFormTextField.setText("");
        isbnFormTextField.setText("");
        nameFormTextField.setText("");
        priceFormTextField.setText("");
    }
    
    private void actulizarProducto(Detail detail, java.awt.event.ActionEvent event){
        int reply = JOptionPane.showConfirmDialog(
            this, "¿Seguro quiere actualizar el producto?",
            "", JOptionPane.YES_NO_OPTION
        );
        
        if( reply == JOptionPane.YES_OPTION)
        {
            ResponseUpdateProd res = conection.updateProd(user, pass, detail);
            int typeMessa = (res.getCode() == 203 ) 
                    ? JOptionPane.INFORMATION_MESSAGE : JOptionPane.ERROR_MESSAGE;
            
            showMessage(String.valueOf(res.getCode()), res.getMessage(), typeMessa);
            
            if(res.getCode() == 203)
            {
                changeCard(jLayeredPane2, operations);
                searchIsbnBtnActionPerformed(event);
                clearForm();
            }
        }
    }
    
    private void setProdcut(Detail detail,  java.awt.event.ActionEvent event){
        int reply = JOptionPane.showConfirmDialog(
            this, "¿Seguro quiere registrar el producto?",
            "", JOptionPane.YES_NO_OPTION
        );
        
        if( reply == JOptionPane.YES_OPTION)
        {
            ResponseSetProd res = conection.setProd(user, pass, detail);
          
            int typeMessa = (res.getCode() == 202 )
                    ? JOptionPane.INFORMATION_MESSAGE : JOptionPane.ERROR_MESSAGE;
            
            showMessage(String.valueOf(res.getCode()), res.getMessage(), typeMessa);
            
            if(res.getCode() == 202)
            {
                changeCard(jLayeredPane2, operations);
                isbnTextField.setText(detail.getIsbn());
                searchIsbnBtnActionPerformed(event);
                clearForm();
            }
        }
    }
    
    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        if( proDetails != null)
        {
            int reply = JOptionPane.showConfirmDialog(
                    this, "¿Estas seguro de eliminar prodcuto?",
                    "", JOptionPane.YES_NO_OPTION);
            if (reply == JOptionPane.YES_OPTION)
            {
                ResponseDeleteProd res = conection.deleteProd(user, pass, proDetails.getIsbn());
            
                if (res.getCode() == 204)
                {
                    showMessage(String.valueOf(res.getCode()), 
                            res.getMessage(),JOptionPane.INFORMATION_MESSAGE);
                    isbnTextField.setText("");
                    detailTextArea.setText("");
                }
                else
                {
                    showMessage(String.valueOf(res.getCode()), 
                            res.getMessage(),JOptionPane.ERROR_MESSAGE);
                    detailTextArea.setText("");
                }
            }
        }
        else
        {
            showMessage("-1", "Prodcuton no seleccionado", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_deleteButtonActionPerformed

    private void createButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createButtonActionPerformed
                
        titleFormLabel.setText("Crear Producto");
        stateForm = StateForm.CREATE_FORM;
        changeCard(jLayeredPane2, FormProduct);
    }//GEN-LAST:event_createButtonActionPerformed

    private void updatePassMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatePassMenuItemActionPerformed
        changeCard(jLayeredPane2, updatePassPanel);
    }//GEN-LAST:event_updatePassMenuItemActionPerformed

    private void clearFormUpdatePass(){
        currentPassTextField.setText("");
        newPassTextField.setText("");
        confiPassTextField.setText("");    
    }
    
    private void btnIniciarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniciarSesionActionPerformed
        
        rol = String.valueOf(categoFormComBox.getSelectedItem());
        
        ResponseUpdatePass res =  conection.updatePass(
            userTextField.getText(),
            String.valueOf(passTextField.getPassword()),
            "");

        // if the code is 502 this mean that the user & pass is right
        if( res.getCode() == 502 )
        {
            user = userTextField.getText();
            pass = String.valueOf(passTextField.getPassword());
            userLabel.setText(user);
            changeCard(jLayeredPane2, operations);
        }
        else
        {
            user = "";
            pass = "";
            showMessage(String.valueOf(res.getCode()), 
                    res.getMessage(), JOptionPane.ERROR_MESSAGE);
        }
        
        if( rol == "Ventas")
        {
            updateButton.setVisible(false);
            createButton.show(false);
            deleteButton.show(false);
        }
        else
        {
            updateButton.setEnabled(true);
            createButton.setEnabled(true);
            deleteButton.setEnabled(true);
        }

        userTextField.setText("");
        passTextField.setText("");
    }//GEN-LAST:event_btnIniciarSesionActionPerformed

    private void aceptButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aceptButtonActionPerformed

        String category = String.valueOf(categoFormComBox.getSelectedItem());
        Detail producto = new Detail(
            Integer.parseInt(yearFormTextField.getText()),
            authorFormTextField.getText(),
            editorialFormTextField.getText(),
            category+isbnFormTextField.getText(),
            nameFormTextField.getText(),
            priceFormTextField.getText()
        );

        switch (stateForm){
            case UPDATE_FORM: actulizarProducto(producto, evt); break;
            case CREATE_FORM: setProdcut(producto, evt); break;
        }
    }//GEN-LAST:event_aceptButtonActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        int reply = JOptionPane.showConfirmDialog(
            this, "¿Estas seguro?",
            "", JOptionPane.YES_NO_OPTION
        );

        if (reply == JOptionPane.YES_OPTION)
        {
            changeCard(jLayeredPane2, operations);
        }
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void categoryTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_categoryTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_categoryTextFieldActionPerformed

    private void cancelUpdatePassBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelUpdatePassBtnActionPerformed
        int reply = JOptionPane.showConfirmDialog(
            this, "¿Seguro quiere cancelar?",
            "", JOptionPane.YES_NO_OPTION
        );

        if( reply == JOptionPane.YES_OPTION)
        changeCard(jLayeredPane2, operations);
    }//GEN-LAST:event_cancelUpdatePassBtnActionPerformed

    private void updatePassBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatePassBtnActionPerformed
        int reply = JOptionPane.showConfirmDialog(
            this, "¿Seguro quiere acntualizar contraseña?",
            "", JOptionPane.YES_NO_OPTION
        );
        
        String current =  String.valueOf(currentPassTextField.getPassword());
        String newPass =  String.valueOf(newPassTextField.getPassword());
        String confiPass =  String.valueOf(confiPassTextField.getPassword());

        if( reply == JOptionPane.YES_OPTION)
        if ( current.length() <= 0 ||
             newPass.length() <= 0 ||
             confiPass.length()  <= 0 )
        {
            showMessage("-1", "Campos vacios", JOptionPane.ERROR_MESSAGE);
        }
        else
        {
            if (newPass.equals(confiPass) )
            {
                ResponseUpdatePass res = conection.updatePass(
                    user, current, newPass);

                clearFormUpdatePass();

                int typeMessage = (res.getCode()==400)
                ? JOptionPane.INFORMATION_MESSAGE
                : JOptionPane.ERROR_MESSAGE;

                showMessage(String.valueOf(res.getCode()), res.getMessage(),
                    typeMessage);

                changeCard(jLayeredPane2, operations);
            }
            else
            {
                showMessage("-1", "Las contraeñas no coinciden", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_updatePassBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel FormProduct;
    private javax.swing.JButton aceptButton;
    private javax.swing.JTextField authorFormTextField;
    private javax.swing.JButton btnIniciarSesion;
    private javax.swing.JButton cancelButton;
    private javax.swing.JButton cancelUpdatePassBtn;
    private javax.swing.JComboBox<String> categoFormComBox;
    private javax.swing.JTextField categoryTextField;
    private javax.swing.JPasswordField confiPassTextField;
    private javax.swing.JButton createButton;
    private javax.swing.JPasswordField currentPassTextField;
    private javax.swing.JButton deleteButton;
    private javax.swing.JPanel detailProdJPanel;
    private javax.swing.JTextArea detailTextArea;
    private javax.swing.JTextField editorialFormTextField;
    private javax.swing.JTextField isbnFormTextField;
    private javax.swing.JTextField isbnTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLayeredPane jLayeredPane2;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JPanel login;
    private javax.swing.JLabel logoLabel;
    private javax.swing.JLabel logoUserLabel;
    private javax.swing.JMenuBar menu;
    private javax.swing.JTextField nameFormTextField;
    private javax.swing.JPasswordField newPassTextField;
    private javax.swing.JPanel operations;
    private javax.swing.JLayeredPane operationsLayeredPane;
    private javax.swing.JPasswordField passTextField;
    private javax.swing.JTextField priceFormTextField;
    private javax.swing.JPanel prodsCateJPanel;
    private javax.swing.JTextArea prodsCateTextArea;
    private javax.swing.JComboBox<String> rolesComboBox;
    private javax.swing.JButton searchCategoryBtn;
    private javax.swing.JButton searchIsbnBtn;
    private javax.swing.JLabel stateLabel;
    private javax.swing.JLabel titleFormLabel;
    private javax.swing.JButton updateButton;
    private javax.swing.JButton updatePassBtn;
    private javax.swing.JMenuItem updatePassMenuItem;
    private javax.swing.JPanel updatePassPanel;
    private javax.swing.JLabel userIconLabel;
    private javax.swing.JLabel userLabel;
    private javax.swing.JTextField userTextField;
    private javax.swing.JTextField yearFormTextField;
    // End of variables declaration//GEN-END:variables
}
