/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.proyecto_p1_rest;


import entities.*;
import java.awt.Dimension;
import java.awt.Image;
import main.Connection;
import responses.*;

import java.util.ArrayList;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLayeredPane;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author jose
 */
public class Principal extends javax.swing.JFrame {
    
    ImageIcon logo = new ImageIcon("imgs/logo.jpg");
    ImageIcon avatar = new ImageIcon("imgs/avatar.png");
    private String user = "pruebas2", pass ="12345678b";
    private enum StateForm { UPDATE_FORM, CREATE_FORM };
    private enum Categoria { CMS, MGS, LBS };
    private StateForm stateForm;
    private Connection conection;
    ResponseGetDetails resProdDetails;
    Detail proDetails;

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        conection = new Connection();
        
        categoFormComBox.removeAllItems();
        categoFormComBox.addItem("CMS");
        categoFormComBox.addItem("MGS");
        categoFormComBox.addItem("LBS");
        
        Image logoScaled = logo.getImage().getScaledInstance(100, 100, Image.SCALE_SMOOTH);
        Icon logoIcon = new ImageIcon(logoScaled);
        logoLabel.setIcon(logoIcon);
        
        Image imgAvatar = avatar.getImage().getScaledInstance(30, 30, Image.SCALE_SMOOTH);
        Icon iconAvatar = new ImageIcon(imgAvatar);
        userIconLabel.setIcon(iconAvatar);
    }
    
    private void changeCard(JLayeredPane layedPanel, JPanel panel) {
        layedPanel.removeAll();
        layedPanel.add(panel);
        layedPanel.repaint();
        layedPanel.revalidate();
    }
    
    private void changeState(String code, String message )
    {
        stateLabel.setText(code+" "+message);
    }
    
    private void showMessage(String code, String mesage, int opcion){
        changeState(code, mesage);
        
        String auxMessage = (code == "-1") ? "" : "Code: "+code+"\n"+"Message: ";
        JOptionPane.showMessageDialog(
                this, 
                auxMessage+mesage, 
                (code == "-1")?"":code, 
                opcion);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane2 = new javax.swing.JLayeredPane();
        login = new javax.swing.JPanel();
        btnIniciarSesion = new javax.swing.JButton();
        userTextField = new javax.swing.JTextField();
        passTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        logoLabel = new javax.swing.JLabel();
        operations = new javax.swing.JPanel();
        isbnTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        searchIsbnBtn = new javax.swing.JButton();
        searchCategoryBtn = new javax.swing.JButton();
        operationsLayeredPane = new javax.swing.JLayeredPane();
        detailProdJPanel = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        detailTextArea = new javax.swing.JTextArea();
        updateButton = new javax.swing.JButton();
        deleteButton = new javax.swing.JButton();
        createButton = new javax.swing.JButton();
        prodsCateJPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        prodsCateTextArea = new javax.swing.JTextArea();
        jSeparator2 = new javax.swing.JSeparator();
        categoryTextField = new javax.swing.JTextField();
        FormProduct = new javax.swing.JPanel();
        titleFormLabel = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        isbnFormTextField = new javax.swing.JTextField();
        nameFormTextField = new javax.swing.JTextField();
        authorFormTextField = new javax.swing.JTextField();
        editorialFormTextField = new javax.swing.JTextField();
        yearFormTextField = new javax.swing.JTextField();
        priceFormTextField = new javax.swing.JTextField();
        cancelButton = new javax.swing.JButton();
        aceptButton = new javax.swing.JButton();
        categoFormComBox = new javax.swing.JComboBox<>();
        updatePassPanel = new javax.swing.JPanel();
        newPassTextField = new javax.swing.JTextField();
        confimPassTextField = new javax.swing.JTextField();
        currentPassTextField = new javax.swing.JTextField();
        updatePassBtn = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        cancelUpdatePassBtn = new javax.swing.JButton();
        btnIngresar = new javax.swing.JButton();
        stateLabel = new javax.swing.JLabel();
        userLabel = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        userIconLabel = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        menu = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        updatePassMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("David & Joshep SA de CV");
        setPreferredSize(new java.awt.Dimension(600, 450));

        jLayeredPane2.setLayout(new java.awt.CardLayout());

        btnIniciarSesion.setText("Inisiar Sesion");
        btnIniciarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIniciarSesionActionPerformed(evt);
            }
        });

        passTextField1.setForeground(new java.awt.Color(200, 204, 198));

        jLabel1.setText("Usuario");

        jLabel2.setText("Contraseña");
        jLabel2.setToolTipText("");

        logoLabel.setAlignmentY(0.0F);
        logoLabel.setMaximumSize(new java.awt.Dimension(100, 100));

        javax.swing.GroupLayout loginLayout = new javax.swing.GroupLayout(login);
        login.setLayout(loginLayout);
        loginLayout.setHorizontalGroup(
            loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginLayout.createSequentialGroup()
                .addGap(136, 136, 136)
                .addGroup(loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(passTextField1)
                    .addComponent(userTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(210, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loginLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loginLayout.createSequentialGroup()
                        .addComponent(btnIniciarSesion)
                        .addGap(207, 207, 207))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loginLayout.createSequentialGroup()
                        .addComponent(logoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(267, 267, 267))))
        );
        loginLayout.setVerticalGroup(
            loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loginLayout.createSequentialGroup()
                .addContainerGap(86, Short.MAX_VALUE)
                .addComponent(logoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(userTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(passTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addComponent(btnIniciarSesion)
                .addGap(41, 41, 41))
        );

        jLayeredPane2.add(login, "card3");

        jLabel3.setText("ISBN");

        jLabel4.setText("Categorias");

        searchIsbnBtn.setText("Buscar");
        searchIsbnBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchIsbnBtnActionPerformed(evt);
            }
        });

        searchCategoryBtn.setText("Buscar");
        searchCategoryBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchCategoryBtnActionPerformed(evt);
            }
        });

        operationsLayeredPane.setLayout(new java.awt.CardLayout());

        detailTextArea.setColumns(20);
        detailTextArea.setRows(5);
        jScrollPane2.setViewportView(detailTextArea);

        updateButton.setText("Actualizar");
        updateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateButtonActionPerformed(evt);
            }
        });

        deleteButton.setText("Eliminar");
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });

        createButton.setText("Crear Producto");
        createButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout detailProdJPanelLayout = new javax.swing.GroupLayout(detailProdJPanel);
        detailProdJPanel.setLayout(detailProdJPanelLayout);
        detailProdJPanelLayout.setHorizontalGroup(
            detailProdJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, detailProdJPanelLayout.createSequentialGroup()
                .addContainerGap(453, Short.MAX_VALUE)
                .addGroup(detailProdJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(updateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(createButton))
                .addGap(54, 54, 54))
            .addGroup(detailProdJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(detailProdJPanelLayout.createSequentialGroup()
                    .addGap(73, 73, 73)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(263, Short.MAX_VALUE)))
        );
        detailProdJPanelLayout.setVerticalGroup(
            detailProdJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(detailProdJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(updateButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(deleteButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 87, Short.MAX_VALUE)
                .addComponent(createButton)
                .addGap(32, 32, 32))
            .addGroup(detailProdJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(detailProdJPanelLayout.createSequentialGroup()
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 32, Short.MAX_VALUE)))
        );

        operationsLayeredPane.add(detailProdJPanel, "card2");

        prodsCateTextArea.setColumns(20);
        prodsCateTextArea.setRows(5);
        jScrollPane1.setViewportView(prodsCateTextArea);

        javax.swing.GroupLayout prodsCateJPanelLayout = new javax.swing.GroupLayout(prodsCateJPanel);
        prodsCateJPanel.setLayout(prodsCateJPanelLayout);
        prodsCateJPanelLayout.setHorizontalGroup(
            prodsCateJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 637, Short.MAX_VALUE)
            .addGroup(prodsCateJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(prodsCateJPanelLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 413, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        prodsCateJPanelLayout.setVerticalGroup(
            prodsCateJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 237, Short.MAX_VALUE)
            .addGroup(prodsCateJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(prodsCateJPanelLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        operationsLayeredPane.add(prodsCateJPanel, "card3");

        javax.swing.GroupLayout operationsLayout = new javax.swing.GroupLayout(operations);
        operations.setLayout(operationsLayout);
        operationsLayout.setHorizontalGroup(
            operationsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(operationsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(operationsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(operationsLayeredPane, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jSeparator2)
                    .addGroup(operationsLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(isbnTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(searchIsbnBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(categoryTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(searchCategoryBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        operationsLayout.setVerticalGroup(
            operationsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(operationsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(operationsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(searchIsbnBtn)
                    .addComponent(isbnTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(categoryTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchCategoryBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(operationsLayeredPane, javax.swing.GroupLayout.PREFERRED_SIZE, 203, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLayeredPane2.add(operations, "card2");

        titleFormLabel.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        titleFormLabel.setText("TITLE-FORM");

        jLabel6.setText("Nombre");

        jLabel7.setText("Autor");

        jLabel8.setText("Editorial");

        jLabel9.setText("Año");

        jLabel10.setText("Precio");

        jLabel11.setText("ISBN");

        cancelButton.setText("Cancelar");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        aceptButton.setText("Aceptar");
        aceptButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aceptButtonActionPerformed(evt);
            }
        });

        categoFormComBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout FormProductLayout = new javax.swing.GroupLayout(FormProduct);
        FormProduct.setLayout(FormProductLayout);
        FormProductLayout.setHorizontalGroup(
            FormProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FormProductLayout.createSequentialGroup()
                .addGroup(FormProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(FormProductLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(aceptButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cancelButton))
                    .addGroup(FormProductLayout.createSequentialGroup()
                        .addGap(132, 132, 132)
                        .addGroup(FormProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(FormProductLayout.createSequentialGroup()
                                .addComponent(titleFormLabel)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(FormProductLayout.createSequentialGroup()
                                .addGroup(FormProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel9))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(FormProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(FormProductLayout.createSequentialGroup()
                                        .addComponent(yearFormTextField)
                                        .addGap(27, 27, 27)
                                        .addComponent(jLabel10)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(priceFormTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(FormProductLayout.createSequentialGroup()
                                        .addComponent(categoFormComBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(isbnFormTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(nameFormTextField)
                                    .addComponent(authorFormTextField)
                                    .addComponent(editorialFormTextField))))))
                .addGap(203, 203, 203))
        );
        FormProductLayout.setVerticalGroup(
            FormProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FormProductLayout.createSequentialGroup()
                .addComponent(titleFormLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(FormProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(isbnFormTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(categoFormComBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(FormProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(nameFormTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(FormProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(authorFormTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(FormProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(editorialFormTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(FormProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(yearFormTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(priceFormTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addGap(18, 18, 18)
                .addGroup(FormProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelButton)
                    .addComponent(aceptButton))
                .addGap(0, 27, Short.MAX_VALUE))
        );

        jLayeredPane2.add(FormProduct, "card4");

        updatePassBtn.setText("Cambiar contraseña");
        updatePassBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatePassBtnActionPerformed(evt);
            }
        });

        jLabel12.setText("Actual contrseña");

        jLabel13.setText("Confirmar contrseña");

        jLabel14.setText("Nueva contrseña");

        jLabel15.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        jLabel15.setText("Cambiar contraseña");

        cancelUpdatePassBtn.setText("Cancelar");
        cancelUpdatePassBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelUpdatePassBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout updatePassPanelLayout = new javax.swing.GroupLayout(updatePassPanel);
        updatePassPanel.setLayout(updatePassPanelLayout);
        updatePassPanelLayout.setHorizontalGroup(
            updatePassPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(updatePassPanelLayout.createSequentialGroup()
                .addContainerGap(180, Short.MAX_VALUE)
                .addGroup(updatePassPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15)
                    .addGroup(updatePassPanelLayout.createSequentialGroup()
                        .addGroup(updatePassPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(updatePassPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(updatePassPanelLayout.createSequentialGroup()
                                .addComponent(updatePassBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cancelUpdatePassBtn))
                            .addGroup(updatePassPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(newPassTextField)
                                .addComponent(confimPassTextField)
                                .addComponent(currentPassTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(59, 59, 59))
        );
        updatePassPanelLayout.setVerticalGroup(
            updatePassPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, updatePassPanelLayout.createSequentialGroup()
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addGroup(updatePassPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(currentPassTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(updatePassPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(newPassTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(updatePassPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(confimPassTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addGap(45, 45, 45)
                .addGroup(updatePassPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(updatePassBtn)
                    .addComponent(cancelUpdatePassBtn))
                .addContainerGap())
        );

        jLayeredPane2.add(updatePassPanel, "card5");

        btnIngresar.setText("Ingresar ");
        btnIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarActionPerformed(evt);
            }
        });

        stateLabel.setText("state");

        userLabel.setToolTipText("");

        jMenu2.setText("Sesion");

        jMenuItem1.setText("Cerrar sesion");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem1);

        updatePassMenuItem.setText("Actualizar Contraseña");
        updatePassMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatePassMenuItemActionPerformed(evt);
            }
        });
        jMenu2.add(updatePassMenuItem);

        menu.add(jMenu2);

        setJMenuBar(menu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jSeparator1)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator4)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(stateLabel)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLayeredPane2)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(userIconLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(userLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnIngresar, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(12, 12, 12))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(userLabel)
                    .addComponent(btnIngresar)
                    .addComponent(userIconLabel))
                .addGap(17, 17, 17)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLayeredPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(stateLabel)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void searchIsbnBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchIsbnBtnActionPerformed

        if(isbnTextField.getText().length() > 0)
        {
            resProdDetails = conection.getDetails(user, pass, isbnTextField.getText());
                    
            if (resProdDetails.isComplete()) 
            {
                proDetails = resProdDetails.getDetail();
                String info = "";
                info += "IBNS           " + proDetails.getIsbn() + "\n";
                info += "Nombre         " + proDetails.getName() + "\n";
                info += "Author         " + proDetails.getAuthor() + "\n";
                info += "Editorial      " + proDetails.getEditorial() + "\n";
                info += "Precio         " + proDetails.getPrice() + "\n";
                info += "Año            " + proDetails.getYear() + "\n";
                info += "Oferta         " + String.valueOf(resProdDetails.getOffer());
                detailTextArea.setText(info);
                changeCard(operationsLayeredPane, detailProdJPanel);
                changeState(
                        String.valueOf(resProdDetails.getCode()), 
                        resProdDetails.getMessage());
            }
            else
            {
                isbnTextField.setText("");
                showMessage(
                        String.valueOf(resProdDetails.getCode()), 
                        resProdDetails.getMessage(),
                        JOptionPane.ERROR_MESSAGE);
            }
        }
        else
        {
            showMessage("-1", 
                    "El cuadrode texto ISBN esta vacio", 
                    JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_searchIsbnBtnActionPerformed

    private void btnIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarActionPerformed
        jLayeredPane2.removeAll();
        jLayeredPane2.add(this.login);
        jLayeredPane2.repaint();
        jLayeredPane2.revalidate();
    }//GEN-LAST:event_btnIngresarActionPerformed

    private void searchCategoryBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchCategoryBtnActionPerformed
        if( categoryTextField.getText().length() > 0)
        {
            ResponseGetProd res = conection.getProd(user, pass, categoryTextField.getText());
        
            if (res.isComplete()) {
                ArrayList<Product> products = res.getProducts();
                String data = "";
            
                for (Product product : products) 
                    data += product.getIsbn() + "\t" + product.getName() + "\n";
            
                prodsCateTextArea.setText(data);
                System.out.println(data);
                changeCard(operationsLayeredPane, prodsCateJPanel);
            }
            else
            {
                categoryTextField.setText("");
                JOptionPane.showMessageDialog(
                    this, String.valueOf(res.getCode())+" "+res.getMessage(), 
                    res.getStatus(), JOptionPane.ERROR_MESSAGE);
            }
            changeState(String.valueOf(res.getCode()), res.getMessage());
        }
        else
        {
            changeState("1", "Cuadro de texto CATEGORIA vacio");
            JOptionPane.showMessageDialog(
                    this, "Cuadro de texto CATEGORIA vacio", 
                    "", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_searchCategoryBtnActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        user = "";
        pass = "";
        changeState(String.valueOf(1), "Sesión finalizada");
        changeCard(jLayeredPane2, login);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void updateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateButtonActionPerformed
      
        stateForm = StateForm.UPDATE_FORM;
        if( proDetails != null)
        {
            titleFormLabel.setText("Actualizar producto");
            
            switch(proDetails.getIsbn().substring(0, 3))
            {
                case "CMS" : categoFormComBox.setSelectedIndex(0); break;
                case "MGS" : categoFormComBox.setSelectedIndex(1); break;
                case "LBS" : categoFormComBox.setSelectedIndex(2); break;
            }
            isbnFormTextField.setText(proDetails.getIsbn().substring(3));
            nameFormTextField.setText(proDetails.getName());
            authorFormTextField.setText(proDetails.getAuthor());
            editorialFormTextField.setText(proDetails.getEditorial());
            yearFormTextField.setText(String.valueOf(proDetails.getYear()));
            priceFormTextField.setText(proDetails.getPrice());

            changeCard(jLayeredPane2, FormProduct);
        }
        else
        {
            JOptionPane.showMessageDialog(
                this, "Ningún producto seleccionado",
                "", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_updateButtonActionPerformed

    private void clearForm(){
        yearFormTextField.setText("");
        authorFormTextField.setText("");
        editorialFormTextField.setText("");
        isbnFormTextField.setText("");
        nameFormTextField.setText("");
        priceFormTextField.setText("");
    }
    
    private void actulizarProducto(Detail detail, java.awt.event.ActionEvent event){
        int reply = JOptionPane.showConfirmDialog(
            this, "¿Seguro quiere actualizar el producto?",
            "", JOptionPane.YES_NO_OPTION
        );
        
        if( reply == JOptionPane.YES_OPTION)
        {
            ResponseUpdateProd res = conection.updateProd(user, pass, detail);
            int typeMessa = (res.getCode() == 203 ) 
                    ? JOptionPane.INFORMATION_MESSAGE : JOptionPane.ERROR_MESSAGE;
            
            showMessage(String.valueOf(res.getCode()), res.getMessage(), typeMessa);
            
            if(res.getCode() == 203)
            {
                changeCard(jLayeredPane2, operations);
                searchIsbnBtnActionPerformed(event);
                clearForm();
            }
        }
    }
    
    private void setProdcut(Detail detail,  java.awt.event.ActionEvent event){
        int reply = JOptionPane.showConfirmDialog(
            this, "¿Seguro quiere registrar el producto?",
            "", JOptionPane.YES_NO_OPTION
        );
        
        if( reply == JOptionPane.YES_OPTION)
        {
            ResponseSetProd res = conection.setProd(user, pass, detail);
          
            int typeMessa = (res.getCode() == 202 )
                    ? JOptionPane.INFORMATION_MESSAGE : JOptionPane.ERROR_MESSAGE;
            
            showMessage(String.valueOf(res.getCode()), res.getMessage(), typeMessa);
            
            if(res.getCode() == 202)
            {
                changeCard(jLayeredPane2, operations);
                isbnTextField.setText(detail.getIsbn());
                searchIsbnBtnActionPerformed(event);
                clearForm();
            }
        }
    }
    
    private void aceptButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aceptButtonActionPerformed

        String category = String.valueOf(categoFormComBox.getSelectedItem());
        Detail producto = new Detail(
                Integer.parseInt(yearFormTextField.getText()),
                authorFormTextField.getText(),
                editorialFormTextField.getText(),
                category+isbnFormTextField.getText(),
                nameFormTextField.getText(),
                priceFormTextField.getText()
        );
        
        switch (stateForm){
            case UPDATE_FORM: actulizarProducto(producto, evt); break;
            case CREATE_FORM: setProdcut(producto, evt); break;
        }
    }//GEN-LAST:event_aceptButtonActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        int reply = JOptionPane.showConfirmDialog(
            this, "¿Estas seguro?",
            "", JOptionPane.YES_NO_OPTION
        );

        if (reply == JOptionPane.YES_OPTION)
        {
            changeCard(jLayeredPane2, operations);
        }
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        if( proDetails != null)
        {
            int reply = JOptionPane.showConfirmDialog(
                    this, "¿Estas seguro de eliminar prodcuto?",
                    "", JOptionPane.YES_NO_OPTION);
            if (reply == JOptionPane.YES_OPTION)
            {
                ResponseDeleteProd res = conection.deleteProd(user, pass, proDetails.getIsbn());
            
                if (res.getCode() == 204)
                {
                    showMessage(String.valueOf(res.getCode()), 
                            res.getMessage(),JOptionPane.INFORMATION_MESSAGE);
                }
                else
                {
                    showMessage(String.valueOf(res.getCode()), 
                            res.getMessage(),JOptionPane.ERROR_MESSAGE);
                    detailTextArea.setText("");
                }
            }
        }
        else
        {
            showMessage("-1", "Prodcuton no seleccionado", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_deleteButtonActionPerformed

    private void createButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createButtonActionPerformed
                
        titleFormLabel.setText("Crear Producto");
        stateForm = StateForm.CREATE_FORM;
        changeCard(jLayeredPane2, FormProduct);
    }//GEN-LAST:event_createButtonActionPerformed

    private void updatePassMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatePassMenuItemActionPerformed
        changeCard(jLayeredPane2, updatePassPanel);
    }//GEN-LAST:event_updatePassMenuItemActionPerformed

    private void cancelUpdatePassBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelUpdatePassBtnActionPerformed
        int reply = JOptionPane.showConfirmDialog(
            this, "¿Seguro quiere cancelar?",
            "", JOptionPane.YES_NO_OPTION
        );
        
        if( reply == JOptionPane.YES_OPTION)
            changeCard(jLayeredPane2, operations);
    }//GEN-LAST:event_cancelUpdatePassBtnActionPerformed

    private void clearFormUpdatePass(){
        currentPassTextField.setText("");
        newPassTextField.setText("");
        confimPassTextField.setText("");    
    }
    
    private void updatePassBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatePassBtnActionPerformed
        int reply = JOptionPane.showConfirmDialog(
            this, "¿Seguro quiere acntualizar contraseña?",
            "", JOptionPane.YES_NO_OPTION
        );
        
        if( reply == JOptionPane.YES_OPTION)
            if (    currentPassTextField.getText().length() <= 0 ||
                    newPassTextField.getText().length()     <= 0 ||
                    confimPassTextField.getText().length()  <= 0 )
            {
                showMessage("-1", "Campos vacios", JOptionPane.ERROR_MESSAGE);
            }
            else
            {
                if (newPassTextField.getText().equals(confimPassTextField.getText()) )
                {
                    ResponseUpdatePass res = conection.updatePass(
                        user, 
                        currentPassTextField.getText(), 
                        newPassTextField.getText());
                
                    clearFormUpdatePass();
                
                    int typeMessage = (res.getCode()==400)
                        ? JOptionPane.INFORMATION_MESSAGE
                        : JOptionPane.ERROR_MESSAGE;
            
                    showMessage(String.valueOf(res.getCode()), res.getMessage(), 
                    typeMessage);
                
                    changeCard(jLayeredPane2, operations);
                }
                else
                {
                    showMessage("-1", "Las contraeñas no coinciden", JOptionPane.ERROR_MESSAGE);
                }
        }
    }//GEN-LAST:event_updatePassBtnActionPerformed

    private void btnIniciarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniciarSesionActionPerformed
        
        ResponseUpdatePass res =  conection.updatePass(
            userTextField.getText(),
            passTextField1.getText(),
            "");

        // if the code is 502 this mean
        // that the user & pass is right
        if( res.getCode() == 502 )
        {
            user = userTextField.getText();
            pass = passTextField1.getText();
            userLabel.setText(user);
            changeCard(jLayeredPane2, operations);
        }
        else
        {
            user = "";
            pass = "";
            showMessage(String.valueOf(res.getCode()), 
                    res.getMessage(), JOptionPane.ERROR_MESSAGE);
        }

        userTextField.setText("");
        userTextField.setText("");
    }//GEN-LAST:event_btnIniciarSesionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel FormProduct;
    private javax.swing.JButton aceptButton;
    private javax.swing.JTextField authorFormTextField;
    private javax.swing.JButton btnIngresar;
    private javax.swing.JButton btnIniciarSesion;
    private javax.swing.JButton cancelButton;
    private javax.swing.JButton cancelUpdatePassBtn;
    private javax.swing.JComboBox<String> categoFormComBox;
    private javax.swing.JTextField categoryTextField;
    private javax.swing.JTextField confimPassTextField;
    private javax.swing.JButton createButton;
    private javax.swing.JTextField currentPassTextField;
    private javax.swing.JButton deleteButton;
    private javax.swing.JPanel detailProdJPanel;
    private javax.swing.JTextArea detailTextArea;
    private javax.swing.JTextField editorialFormTextField;
    private javax.swing.JTextField isbnFormTextField;
    private javax.swing.JTextField isbnTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLayeredPane jLayeredPane2;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JPanel login;
    private javax.swing.JLabel logoLabel;
    private javax.swing.JMenuBar menu;
    private javax.swing.JTextField nameFormTextField;
    private javax.swing.JTextField newPassTextField;
    private javax.swing.JPanel operations;
    private javax.swing.JLayeredPane operationsLayeredPane;
    private javax.swing.JTextField passTextField1;
    private javax.swing.JTextField priceFormTextField;
    private javax.swing.JPanel prodsCateJPanel;
    private javax.swing.JTextArea prodsCateTextArea;
    private javax.swing.JButton searchCategoryBtn;
    private javax.swing.JButton searchIsbnBtn;
    private javax.swing.JLabel stateLabel;
    private javax.swing.JLabel titleFormLabel;
    private javax.swing.JButton updateButton;
    private javax.swing.JButton updatePassBtn;
    private javax.swing.JMenuItem updatePassMenuItem;
    private javax.swing.JPanel updatePassPanel;
    private javax.swing.JLabel userIconLabel;
    private javax.swing.JLabel userLabel;
    private javax.swing.JTextField userTextField;
    private javax.swing.JTextField yearFormTextField;
    // End of variables declaration//GEN-END:variables
}
